version: '3'

services:
    php-app:
        container_name: php-app
        build:
            context: .
            dockerfile: ./.docker/php-app/Dockerfile
        volumes:
            - ./app:/var/www/html
            - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        networks:
            - app-network

    webserver:
        container_name: webserver
        image: nginx
        ports:
            - '80:80'
        volumes:
            - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www/html
        restart: always
        networks:
            - app-network
        depends_on:
            - php-app
            - pgs_db
    pgs_db:
        container_name: pgs_db
        image: postgres
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: pguser
            POSTGRES_DB: pgs_db
        volumes:
            - ./db_data/postgresql/data:/var/lib/postgresql/data
        networks:
            - app-network


networks:
    app-network:
        driver: bridge
